sudo: true
dist: xenial
language: python

matrix:
  include:

    - os: linux
      python: "3.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libblas-dev
            - liblapack-dev
      env: MATRIX_EVAL="CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - export "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/use/local/lib"
  - export "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/use/local/lib"

install:
  - mkdir lib
  - git clone --depth=1 https://bitbucket.org/blaze-lib/blaze.git ./lib/blaze
  - pip install -r requirements.txt

script:
  - python setup.py configure --compiler="$CXX" --build-type=DEBUG --blaze=./lib/blaze
  - python setup.py build
